const { exec } = require('child_process');
const path = require('path');
const fs = require('fs');
const zlib = require('zlib');
const cron = require('node-cron');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');

const runDatabaseBackup = () => {
  // 🎯 Wrap the entire function inside a Promise so the controller can AWAIT it properly
  return new Promise((resolve, reject) => {
    const dbName = process.env.DB_NAME || 'lead_crm';
    const dbUser = process.env.DB_USER || 'root';
    const dbPass = process.env.DB_PASSWORD || '';
    const dbHost = process.env.DB_HOST || 'localhost';
    const dbPort = process.env.DB_PORT || '3306';
    
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const backupsDir = path.join(__dirname, '../../backups');
    const rawSqlPath = path.join(backupsDir, `backup-${dbName}-${timestamp}.sql`);
    const compressedGzPath = `${rawSqlPath}.gz`;

    if (!fs.existsSync(backupsDir)) {
      fs.mkdirSync(backupsDir, { recursive: true });
    }

    const wampMysqlDumpPath = `"C:\\wamp64\\bin\\mysql\\mysql9.1.0\\bin\\mysqldump.exe"`; 
    const passFlag = dbPass ? `-p"${dbPass}"` : '';
    const cmd = `${wampMysqlDumpPath} -h ${dbHost} -P ${dbPort} -u ${dbUser} ${passFlag} ${dbName} > "${rawSqlPath}"`;

    exec(cmd, async (error) => {
      if (error) {
        console.error(`[Backup Engine Error]: ${error.message}`);
        return reject(new Error(`WAMP mysqldump failed: ${error.message}`));
      }

      setTimeout(() => {
        try {
          if (!fs.existsSync(rawSqlPath)) {
            return reject(new Error("Raw SQL dump file was not generated by WAMP. Check your MySQL folder path."));
          }

          const rawFileContents = fs.createReadStream(rawSqlPath);
          const destinationStream = fs.createWriteStream(compressedGzPath);
          
          rawFileContents.pipe(zlib.createGzip()).pipe(destinationStream);

          destinationStream.on('finish', async () => {
            try {
              if (fs.existsSync(rawSqlPath)) fs.unlinkSync(rawSqlPath);

              const keyId = process.env.AWS_ACCESS_KEY_ID;
              const hasRealCloudKeys = keyId && !keyId.includes('your_actual') && !keyId.includes('placeholder');

              if (hasRealCloudKeys) {
                const fileStats = fs.statSync(compressedGzPath);
                const fileStream = fs.createReadStream(compressedGzPath);
                
                const s3 = new S3Client({
                  region: process.env.AWS_REGION || 'us-east-1',
                  credentials: { accessKeyId: process.env.AWS_ACCESS_KEY_ID, secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY }
                });

                await s3.send(new PutObjectCommand({
                  Bucket: process.env.AWS_BACKUP_BUCKET_NAME,
                  Key: `database/backup-${dbName}-${timestamp}.sql.gz`,
                  Body: fileStream,
                  ContentLength: fileStats.size,
                  ContentType: 'application/gzip'
                }));

                if (fs.existsSync(compressedGzPath)) fs.unlinkSync(compressedGzPath);
                return resolve({ type: 'cloud', path: filename });
              } else {
                // 🎯 Local backup complete, resolve successfully!
                return resolve({ type: 'local', path: `backups/backup-${dbName}-${timestamp}.sql.gz` });
              }

            } catch (cloudErr) {
              // If cloud fails, retain local file and resolve successfully anyway as fallback!
              console.error(`[Backup Cloud Transit Fault]:`, cloudErr.message);
              return resolve({ type: 'local_fallback', path: compressedGzPath });
            }
          });

        } catch (pipelineErr) {
          if (fs.existsSync(rawSqlPath)) fs.unlinkSync(rawSqlPath);
          return reject(pipelineErr);
        }
      }, 500);
    });
  });
};

cron.schedule('0 2 * * *', () => {
  runDatabaseBackup().catch(err => console.error("Scheduled Backup Failed:", err.message));
});

module.exports = { runDatabaseBackup };